### PR TITLE
Created a dynamic way of creating tiles, using a JSON file.

### LINKED ISSUE #3: Få alle brikkene til å rendre slik vi ønsker

### PR DESCRIPTION
**Pull request by ThomasStorli**
#3 
Most of the tiles are now implemented.

### CODE REVIEW

**Comment by ThomasStorli** [comment]
Added a new dependency: Gson

**Comment by ThomasStorli** [comment]
We still need to add the last tiles before merging.

**Review by Jethuestad — COMMENTED** [review]
Looks good so far!

**Comment by ThomasStorli** [comment]
Wonderful!

**Pull request merged**
